### ISSUE TITLE
Octocats

### ISSUE THREAD

**Issue by JorgePiaggio** [deepu14d/deepu14d#1]
Hi there, here you can find the octocats images, just copy the link of the image and add it to your readme.
[Octocats](https://octodex.github.com/)

For example: 
```<img src="https://octodex.github.com/images/filmtocat.png" title="As you can see, I love cats" width="170">```
<img src="https://octodex.github.com/images/filmtocat.png" title="As you can see, I love cats" width="170">

**Comment by deepu14d** [comment]
Thanks a lot
